### PR TITLE
Fix various issues - improve codebase

### LINKED ISSUE #86: v3: BelongsToManyGetAssociationsMixin should allow FindOptions
`BelongsToManyGetAssociationsMixinOptions` and possibly other associations mixins don't allow to pass in `FindOptions` even though this works perfectly fine.

### LINKED ISSUE #131: Model.increment is missing.
I might create a PR later for this as I already fixed it locally.

### LINKED ISSUE #143: TS2503: Cannot find namespace 'ValidatorJS'
run `tsc`
TS2503: Cannot find namespace 'ValidatorJS'

### PR DESCRIPTION
**Pull request by SimonSchick**
This is another series of small fixes/improvements I made while using the typings, some of which may not be entirely appropriate.

Mainly:
Moved various duplicate options/properties into interfaces (trait likes).
Add a few overloads.
Add missing `increment` static.

Fixes #86
Fixes #131
Fixes #143

### CODE REVIEW

**Comment by SimonSchick** [comment]
Looks like I forgot to run `npm install` in travis, will address shortly.

File: lib/misc-types.d.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
+import { Transaction } from './transaction';
```
Comment (felixfbecker) [inline lib/misc-types.d.ts]: I don't like adding a declaration file that doesn't exist in the source library.

File: lib/query-interface.d.ts [hunk 2]
```diff
@@ -55,46 +56,45 @@ export interface QueryOptions {
...
-  // TODO: force, cascade
+  model: typeof Model;
+}
 
+export interface QueryOptionsWithType {
+  /**
+   * The type of query you are executing. The query type affects how results are formatted before they are
+   * passed back. The type is a string, but `Sequelize.QueryTypes` is provided as convenience shortcuts.
+   */
+  type: 'SELECT' | 'INSERT' | 'UPDATE' | 'DELETE' | string;
```
Comment (felixfbecker) [inline lib/query-interface.d.ts]: If it allows `string`, this type is not any more typesafe than `string`. Same as anything `| any`...

File: typings.json [hunk 3]
```diff
@@ -1,9 +1,5 @@
 {
   "name": "sequelize",
   "main": "index.d.ts",
-  "version": "4.0.0-1",
-  "dependencies": {
-    "bluebird": "registry:npm/bluebird#3.5.0+20170314181206",
-    "validator": "registry:npm/validator#5.7.0+20160912014851"
-  }
+  "version": "4.0.0-1"
```
Comment (felixfbecker) [inline typings.json]: This is a breaking change for `typings` users.

File: package.json [hunk 4]
```diff
@@ -5,8 +5,8 @@
   "description": "Typescript Typings for Sequelize",
   "typings": "index.d.ts",
   "dependencies": {
-    "@types/bluebird": "^3.5.5",
-    "@types/validator": "types/validator#83990944fcc53bcb4b05b347c3cdfcb7aa05b3c7"
```
Comment (felixfbecker) [inline package.json]: there must have been a reason why we used `types/validator`

File: typings.json (hunk 3 above)
Comment (SimonSchick) [reply typings.json]: I kept getting nasty warnings about `typings` being deprecated, and this should work regardless as the typings will be installed automatically via npm's `@types` instead, I testes this in 2 projects and couldn't find any type issues.

File: package.json (hunk 4 above)
Comment (SimonSchick) [reply package.json]: I figured as much but couldn't find any issues, the typings look mostly identical to me, `@types` are more precise/up to date however.

File: lib/misc-types.d.ts (hunk 1 above)
Comment (SimonSchick) [reply lib/misc-types.d.ts]: Do you have a better suggestion? These types are used across multiple files, copy/pasting them into each file would make this a PITA to maintain.

File: lib/query-interface.d.ts (hunk 2 above)
Comment (SimonSchick) [reply lib/query-interface.d.ts]: True, not sure why this is in there, I'll make that use the new enum type instead.

File: package.json (hunk 4 above)
Comment (SimonSchick) [reply package.json]: Actually, they don't even work with the current codebase.

``` "validator": "registry:npm/validator#5.7.0+20160912014851"```

File: typings.json (hunk 3 above)
Comment (SimonSchick) [reply typings.json]: In reference to the `validator` problem, why not just drop support for typings, as mentioned they are deprecated.

Comment (SimonSchick) [reply typings.json]: I will rollback these changes for now, but don't expect them to work, lol.

Comment (felixfbecker) [reply typings.json]: Just because they are deprecated doesn't mean there aren't still people using it.
@blakeembrey do you have stats on this?

**Comment by SimonSchick** [comment]
@felixfbecker poke

File: lib/query-interface.d.ts [hunk 5]
```diff
@@ -21,7 +23,7 @@ export interface QueryOptions {
    */
   transaction?: Transaction;
 
-  /**
+  /*
```
Comment (felixfbecker) [inline lib/query-interface.d.ts]: revert

File: lib/misc-types.d.ts (hunk 1 above)
Comment (felixfbecker) [reply lib/misc-types.d.ts]: Well in the source code the reason why these options are all possible on e.g. the associations is that under the hood they will all call into `Model` methods, so that's where I would put it.

**Comment by SimonSchick** [comment]
Moved the interfaces to the `model` file.

File: typings.json (hunk 3 above)
Comment (blakeembrey) [reply typings.json]: @felixfbecker I do have analytics, but I'd be happy to start removing everything `typings` related. It won't break backward compat thankfully since I was super persistent with hard tagging everything to a specific commit. The only people it'll break for it already warned them about it, and they can always just go back to an old commit until they move to `@types` (but I'm pretty confident this won't be an issue for anyone).

Comment (felixfbecker) [reply typings.json]: Okay, lets remove it then

**Comment by SimonSchick** [comment]
I removed typings but for some reason the build now fails on travis (works locally), I'll try to get this resolved.

**Comment by SimonSchick** [comment]
I also suggest to squash merge this one...

**Comment by SimonSchick** [comment]
@felixfbecker issue has been resolved.

**Comment by SimonSchick** [comment]
ping @felixfbecker

File: test/tsconfig.json [hunk 6]
```diff
@@ -3,14 +3,20 @@
...
     "noEmit": true,
-    "strictNullChecks": true,
+    "strict": true,
+    "baseUrl": ".",
     "typeRoots": [
-      "../typings/globals",
-      "../typings/modules"
-    ]
+      "typings/globals",
+      "typings/modules"
```
Comment (felixfbecker) [inline test/tsconfig.json]: These should be removed if you're removing typings

**Comment by SimonSchick** [comment]
@felixfbecker done, again, I suggest you squash merge, commits got a bit messy.

File: typings.json [hunk 7]
```diff
@@ -3,7 +3,7 @@
   "main": "index.d.ts",
   "version": "4.0.0-1",
   "dependencies": {
-    "bluebird": "registry:npm/bluebird#3.5.0+20170314181206",
-    "validator": "registry:npm/validator#5.7.0+20160912014851"
+        "bluebird": "registry:npm/bluebird#3.5.0+20170314181206",
+        "validator": "registry:npm/validator#5.7.0+20160912014851"
```
Comment (felixfbecker) [inline typings.json]: Remove this file?

File: tsconfig.json [hunk 8]
```diff
@@ -4,25 +4,15 @@
     "module": "commonjs",
     "moduleResolution": "node",
     "noEmit": true,
-    "strictNullChecks": true,
+    "strict": true,
```
Comment (felixfbecker) [inline tsconfig.json]: Imo this is not a good idea because what's included in `strict` changes over time and will break the build in minor typescript updates.

File: lib/utils.d.ts [hunk 9]
```diff
@@ -1,5 +1,5 @@
 
-import parameterValidator = require('./utils/parameter-validator');
+import * as parameterValidator from './utils/parameter-validator';
```
Comment (felixfbecker) [inline lib/utils.d.ts]: Why this change? `parameterValidator` is a function, so this is not correct in regard to ES6 semantics.

File: tsconfig.json (hunk 8 above)
Comment (SimonSchick) [reply tsconfig.json]: Usually these updates enhance type safety so this is a good thing?

File: typings.json (hunk 7 above)
Comment (SimonSchick) [reply typings.json]: Weird, this file doesn't exist on my local FS anymore, looking into it.

File: tsconfig.json (hunk 8 above)
Comment (felixfbecker) [reply tsconfig.json]: That's not the point, builds should be reproducible. I can't fix the build of a hundred repos when a new TS version comes out. The type safety enhancements almost always also trigger false positives.

Comment (felixfbecker) [reply tsconfig.json]: A better approach is to have an org-wide tsconfig as an npm package, and then a bot can do a PR to upgrade it. But that's a bit overkill here.

File: lib/utils.d.ts (hunk 9 above)
Comment (SimonSchick) [reply lib/utils.d.ts]: I think some TS plugin in my editor did that...
I mean, it works so I don't see any harm in it.

Comment (felixfbecker) [reply lib/utils.d.ts]: Not to be to picky, but there are two general objectives here:
- keeping PR change sets as small as possible
- writing understandable, non-confusing code. An import that is broken by ES6 standard is confusing for a new dev reading the code.

Should be easy enough to revert.

Comment (SimonSchick) [reply lib/utils.d.ts]: The same argument could be made for the `Bluebird` import in the codebase as `Bluebird` is also a function and not a namespace.

It was also the only `require` in the entire code base and felt out of place.

But if it makes you happy ¯\\_(ツ)_/¯

Comment (felixfbecker) [reply lib/utils.d.ts]: Yes, you are right about that.
We discussed this at some point in the typings org and agreed on this style, the bluebird import is also wrong.
